# Generated by Django 5.1.7 on 2025-05-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightschedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
    ]
