# Generated by Django 5.1.7 on 2025-05-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_flightschedule_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightschedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
