# Generated by Django 5.1.7 on 2025-05-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_flightreservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightschedule',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
