# Generated by Django 5.1.7 on 2025-05-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_flightschedule_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightschedule',
            name='price',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
