# Generated by Django 5.1.7 on 2025-05-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_flightschedule_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightreservation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled')], default='active', max_length=10),
        ),
    ]
