# Generated by Django 5.1.7 on 2025-05-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_flightreservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightreservation',
            name='flight_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.flightschedule'),
        ),
    ]
